name: Build e Teste do Docker

# Quando o workflow será executado
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona o repositório
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2. Configura o Docker Buildx (para builds avançados)
    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Faz o build da imagem Docker
    - name: Build da imagem Docker
      run: docker build -t meu-app .

    # 4. Roda o container em segundo plano
    - name: Rodar container para teste
      run: docker run -d -p 5000:5000 meu-app

    # 5. Aguarda o app iniciar e testa com curl
    - name: Testar resposta do app
      run: |
        sleep 5
        curl --fail http://localhost:5000
